from .process_table import (
    TRANSFORM_DATA_TEMPLATE,
    IDENTIFY_HEADER_FOOTER_TEMPLATE,
    DESIGN_SCHEMA_TEMPLATE,
    GENERATE_HEADER_TEMPLATE
)

__all__ = [
    "TRANSFORM_DATA_TEMPLATE",
    "IDENTIFY_HEADER_FOOTER_TEMPLATE",
    "DESIGN_SCHEMA_TEMPLATE",
    "GENERATE_HEADER_TEMPLATE"
]